export function createRawSourceRecord({
  store,
  issuer,
  sourceType,
  parentSourceId = null,
  discoveredFromUrl = null,
  url,
  finalUrl,
  linkText = "",
  status = null,
  ok = false,
  contentType = null,
  contentLength = null,
  checksumSha256,
  blobPath,
  metadata = {},
}) {
  return {
    sourceId: store.nextSourceId(issuer.issuerId),
    crawlId: store.crawlId,
    issuerId: issuer.issuerId,
    issuerName: issuer.issuerName,
    strategy: issuer.strategy,
    sourceType,
    parentSourceId,
    cardKey: null,
    url,
    canonicalUrl: finalUrl || url,
    discoveredFromUrl,
    method: "GET",
    status,
    ok,
    contentType,
    contentLength,
    checksumSha256,
    fetchedAt: new Date().toISOString(),
    storage: {
      blobPath,
    },
    metadata: {
      linkText,
      ...metadata,
    },
  };
}
